import { RequestItem } from "./context/SchemaContext";
import { WorkflowState } from "./context/WorkflowContext";

export const FIELD_TYPES = {
  TEXT: "text",
  NUMBER: "number",
  FLOAT: "float",
  CURRENCY: "currency",
  DATE: "date",
  BOOLEAN: "boolean",
  ITEMS: "items",
  DOCUMENTS: "documents",
};

// Date format and field type options
export const DATE_FORMAT_OPTIONS = [
  "MM/DD/YYYY",
  "DD/MM/YYYY",
  "YYYY-MM-DD",
  "MMM DD, YYYY",
];

export const FIELD_TYPES_OPTIONS = [
  { value: FIELD_TYPES.TEXT, label: "Text" },
  { value: FIELD_TYPES.NUMBER, label: "Number" },
  { value: FIELD_TYPES.FLOAT, label: "Float" },
  { value: FIELD_TYPES.CURRENCY, label: "Currency" },
  { value: FIELD_TYPES.DATE, label: "Date" },
  { value: FIELD_TYPES.BOOLEAN, label: "Boolean" },
  { value: FIELD_TYPES.ITEMS, label: "Items" },
  { value: FIELD_TYPES.DOCUMENTS, label: "Documents" },
];

export const PRESET_FIELDS = [
  {
    id: "requestWorkflow",
    type: FIELD_TYPES.TEXT,
    parameter: "Request Workflow",
    isRequired: true,
    readOnly: false,
    defaultField: true,
    isHidden: false,
  },
  {
    id: "requestCreated",
    type: FIELD_TYPES.DATE,
    parameter: "Request Created",
    format: "MM-DD-YYYY",
    isRequired: true,
    readOnly: true,
    defaultField: true,
    isHidden: false,
  },
  {
    id: "requestCreator",
    type: FIELD_TYPES.TEXT,
    parameter: "Request Creator",
    isRequired: true,
    readOnly: true,
    defaultField: true,
    isHidden: false,
  },
  {
    id: "requestNextApprover",
    type: FIELD_TYPES.TEXT,
    parameter: "Next Step Approver",
    isRequired: true,
    readOnly: false,
    defaultField: true,
    isHidden: false,
  },
  {
    id: "requestPrevApprover",
    type: FIELD_TYPES.TEXT,
    parameter: "Previous Approver",
    isRequired: true,
    readOnly: false,
    defaultField: true,
    isHidden: true,
  },
  {
    id: "requestNumber",
    type: FIELD_TYPES.NUMBER,
    parameter: "Request Number",
    isRequired: true,
    readOnly: false,
    defaultField: true,
    isHidden: false,
  },
  {
    id: "requestStatus",
    type: FIELD_TYPES.TEXT,
    parameter: "Request Status",
    isRequired: true,
    readOnly: false,
    defaultField: true,
    isHidden: false,
  },
  {
    id: "contractNumber",
    type: FIELD_TYPES.NUMBER,
    parameter: "Contract Number",
    isRequired: true,
    readOnly: false,
    defaultField: true,
    isHidden: false,
  },
  {
    id: "description",
    type: FIELD_TYPES.TEXT,
    parameter: "Description",
    isRequired: false,
    readOnly: false,
    defaultField: true,
    isHidden: true,
  },
  {
    id: "requestedAwardDate",
    type: FIELD_TYPES.DATE,
    parameter: "Requested Award Date",
    format: "MM-DD-YYYY",
    isRequired: true,
    readOnly: false,
    defaultField: true,
    isHidden: false,
  },
  {
    id: "requestDocuments",
    type: FIELD_TYPES.DOCUMENTS,
    parameter: "Request Documents",
    isRequired: false,
    readOnly: false,
    defaultField: true,
    isHidden: false,
  },
  {
    id: "requestedItems",
    type: FIELD_TYPES.ITEMS,
    parameter: "Requested Items",
    isRequired: true,
    readOnly: false,
    defaultField: true,
    isHidden: true,
  },
];

export const SHIPPING_FIELDS = [
  {
    id: "customerPOCName",
    parameter: "Customer POC Name",
    type: FIELD_TYPES.TEXT,
    isRequired: true,
    readOnly: false,
    defaultField: true,
    isHidden: false,
  },
  {
    id: "customerPOCEmail",
    parameter: "Customer POC Email",
    type: FIELD_TYPES.TEXT,
    isRequired: true,
    readOnly: false,
    defaultField: true,
    isHidden: true,
  },
  {
    id: "attentionTo",
    parameter: "Attention To ( If different )",
    type: FIELD_TYPES.TEXT,
    isRequired: false,
    readOnly: false,
    defaultField: true,
    isHidden: true,
  },
  {
    id: "shippingStreetAddress1",
    parameter: "Shipping Address: Street",
    type: FIELD_TYPES.TEXT,
    isRequired: true,
    readOnly: false,
    defaultField: true,
    isHidden: true,
  },
  {
    id: "shippingStreetAddress2",
    parameter: "Shipping Address: Street 2",
    type: FIELD_TYPES.TEXT,
    isRequired: false,
    readOnly: false,
    defaultField: true,
    isHidden: true,
  },
  {
    id: "shippingAddressCity",
    parameter: "Shipping Address: City",
    type: FIELD_TYPES.TEXT,
    isRequired: true,
    readOnly: false,
    defaultField: true,
    isHidden: true,
  },
  {
    id: "shippingAddressState",
    parameter: "Shipping Address: State",
    type: FIELD_TYPES.TEXT,
    isRequired: true,
    readOnly: false,
    defaultField: true,
    isHidden: true,
  },
  {
    id: "shippingAddressZipcode",
    parameter: "Shipping Address: Zipcode",
    type: FIELD_TYPES.TEXT,
    isRequired: true,
    readOnly: false,
    defaultField: true,
    isHidden: true,
  },
];

// USERS
export enum AccessRole {
  SUPER_ADMIN = "SUPER_ADMIN",
  ADMIN = "ADMIN",
  USER = "USER",
  GUEST = "GUEST",
}

// interface for the Role type.
export interface User {
  Name: string;
  Roles: Array<string>;
  AcceptedTerms: boolean;
  LoggingOut: boolean;
  Tenants: Array<string>;
  IsAdmin: boolean;
  CurrentTenant: string;
}

export const DEFAULT_WORKFLOW: WorkflowState = {
  rootItem: "order-received",
  name: "Default Workflow",
  items: {
    "order-received": {
      id: "order-received",
      name: "Order Received",
      children: ["sourcing"],
      nextApprover: "",
      prevApprover: "",
      easyApproval: true,
    },
    sourcing: {
      id: "sourcing",
      name: "Sourcing",
      children: ["purchasing"],
      nextApprover: "",
      prevApprover: "",
      easyApproval: true,
    },
    purchasing: {
      id: "purchasing",
      name: "Purchasing",
      children: ["order-complete"],
      nextApprover: "",
      prevApprover: "",
      easyApproval: false,
    },
    "order-complete": {
      id: "order-complete",
      name: "Order Complete",
      children: [],
      nextApprover: "",
      prevApprover: "",
      easyApproval: false,
    },
  },
  workflowKey: "default",
  workflowDescription: "Default Template Workflow",
};

export const PRODUCTS: RequestItem[] = [
  {
    product: "HP Workstation",
    amount: 0,
    price: 2467.78,
  },
  {
    product: "Dell XP Desktop",
    amount: 0,
    price: 1276.45,
  },
  {
    product: "Alienware ION Workstation",
    amount: 0,
    price: 3798.82,
  },
  {
    product: "SSD Hardrive: 12TB",
    amount: 0,
    price: 5623.44,
  },
];

export const US_STATES = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
];

// ------------ USERS ------------------//
const all_roles = [
  "CHS_DOCS_ADD",
  "CHS_DOCS_ADD_FOLDER",
  "CHS_DOCS_DELETE",
  "CHS_DOCS_LIST",
  "CHS_DOCS_READ",
  "CHS_DOCS_UPDATE",
  "CHS_ECAT_ACCESS",
  "CHS_ECAT_ADMIN",
  "CHS_ECAT_ORDERING",
  "CHS_ECAT_ORDER_ADMIN",
  "CHS_IDE_ACCESS",
  "CHS_LEIDOS_PROG_MGMT",
  "CHS_PORTAL_ACCESS",
  "CHS_PORTAL_DASHBOARDS_ACCESS",
  "CHS_PORTAL_DOCS_ACCESS",
  "CHS_PORTAL_REQUEST_TRACKER_ACCESS",
  "SERVICE_NOW",
  "TENANT_CHS",
];

const superAdminRoles: string[] = all_roles;
const adminRoles: string[] = ["CHS_PORTAL_ACCESS"];

// USERS is now correctly typed as an array of User.
export const USERS: User[] = [
  {
    Name: "Jane Super",
    Roles: superAdminRoles,
    AcceptedTerms: true,
    LoggingOut: false,
    Tenants: ["TENANT_CHS", "TENANT_F16", "TENANT_DEMO", "TENANT_PACMAN"],
    IsAdmin: true,
    CurrentTenant: "CHS",
  },
  {
    Name: "Kara Admin",
    Roles: adminRoles,
    AcceptedTerms: true,
    LoggingOut: false,
    Tenants: ["TENANT_CHS", "TENANT_F16"],
    IsAdmin: true,
    CurrentTenant: "",
  },
  {
    Name: "Dan User",
    Roles: ["CHS_PORTAL_ACCESS"],
    AcceptedTerms: true,
    LoggingOut: false,
    Tenants: ["TENANT_CHS"],
    IsAdmin: false,
    CurrentTenant: "",
  },
  {
    Name: "Matt User",
    Roles: ["CHS_PORTAL_ACCESS"],
    AcceptedTerms: true,
    LoggingOut: false,
    Tenants: ["TENANT_CHS"],
    IsAdmin: false,
    CurrentTenant: "",
  },
  {
    Name: "Terry User",
    Roles: ["CHS_PORTAL_ACCESS"],
    AcceptedTerms: true,
    LoggingOut: false,
    Tenants: ["TENANT_F16"],
    IsAdmin: false,
    CurrentTenant: "",
  },
  {
    Name: "John Guest",
    Roles: [],
    AcceptedTerms: false,
    LoggingOut: false,
    Tenants: [],
    IsAdmin: false,
    CurrentTenant: "",
  },
];

export const DEFAULT_ROW_DATA = [
  {
    id: 1,
    "Request Workflow": "Purchase Order",
    "Request Created": "05-01-2025",
    "Request Creator": "Alice Admin",
    "Next Step Approver": "Dan User",
    "Previous Approver": "",
    "Request Number": 1001,
    "Request Status": "Pending",
    "Contract Number": 50001,
    Description: "Office supplies",
    "Requested Award Date": "05-11-2025",
    "Request Documents": [],
    "Customer POC Name": "Bob Buyer",
    "Customer POC Email": "bob.buyer@acme.com",
    "Attention To ( If different )": "",
    "Shipping Address: Street": "123 Maple St",
    "Shipping Address: Street 2": "",
    "Shipping Address: City": "Metropolis",
    "Shipping Address: State": "NY",
    "Shipping Address: Zipcode": "10001",
  },
  {
    id: 2,
    "Request Workflow": "Equipment Lease",
    "Request Created": "05-02-2025",
    "Request Creator": "Bob Buyer",
    "Next Step Approver": "Matt User",
    "Previous Approver": "Alice Admin",
    "Request Number": 1002,
    "Request Status": "In Progress",
    "Contract Number": 50002,
    Description: "Field equipment rental",
    "Requested Award Date": "05-12-2025",
    "Request Documents": [],
    "Customer POC Name": "Carol Contact",
    "Customer POC Email": "carol.contact@beta.com",
    "Attention To ( If different )": "Dave Delivery",
    "Shipping Address: Street": "456 Oak St",
    "Shipping Address: Street 2": "Suite 200",
    "Shipping Address: City": "Gotham",
    "Shipping Address: State": "NJ",
    "Shipping Address: Zipcode": "07097",
  },
  {
    id: 3,
    "Request Workflow": "Software License",
    "Request Created": "05-03-2025",
    "Request Creator": "Carol Contact",
    "Next Step Approver": "Terry User",
    "Previous Approver": "Bob Buyer",
    "Request Number": 1003,
    "Request Status": "Approved",
    "Contract Number": 50003,
    Description: "Annual software license",
    "Requested Award Date": "05-13-2025",
    "Request Documents": [],
    "Customer POC Name": "Eve Engineer",
    "Customer POC Email": "eve.engineer@gamma.com",
    "Attention To ( If different )": "",
    "Shipping Address: Street": "789 Pine St",
    "Shipping Address: Street 2": "",
    "Shipping Address: City": "Star City",
    "Shipping Address: State": "CA",
    "Shipping Address: Zipcode": "90001",
  },
  {
    id: 4,
    "Request Workflow": "Maintenance Request",
    "Request Created": "05-04-2025",
    "Request Creator": "Dave Delivery",
    "Next Step Approver": "Kara Admin",
    "Previous Approver": "Carol Contact",
    "Request Number": 1004,
    "Request Status": "Pending",
    "Contract Number": 50004,
    Description: "HVAC system check",
    "Requested Award Date": "05-14-2025",
    "Request Documents": [],
    "Customer POC Name": "Frank Finance",
    "Customer POC Email": "frank.finance@delta.com",
    "Attention To ( If different )": "",
    "Shipping Address: Street": "101 Elm St",
    "Shipping Address: Street 2": "Floor 3",
    "Shipping Address: City": "Central City",
    "Shipping Address: State": "TX",
    "Shipping Address: Zipcode": "73301",
  },
  {
    id: 5,
    "Request Workflow": "Supply Reorder",
    "Request Created": "05-05-2025",
    "Request Creator": "Eve Engineer",
    "Next Step Approver": "Dan User",
    "Previous Approver": "Dave Delivery",
    "Request Number": 1005,
    "Request Status": "In Progress",
    "Contract Number": 50005,
    Description: "Printer toner cartridges",
    "Requested Award Date": "05-15-2025",
    "Request Documents": [],
    "Customer POC Name": "Grace Gopher",
    "Customer POC Email": "grace.gopher@epsilon.com",
    "Attention To ( If different )": "",
    "Shipping Address: Street": "202 Cedar St",
    "Shipping Address: Street 2": "",
    "Shipping Address: City": "Coast City",
    "Shipping Address: State": "WA",
    "Shipping Address: Zipcode": "98004",
  },
  {
    id: 6,
    "Request Workflow": "Purchase Order",
    "Request Created": "05-06-2025",
    "Request Creator": "Frank Finance",
    "Next Step Approver": "Matt User",
    "Previous Approver": "Eve Engineer",
    "Request Number": 1006,
    "Request Status": "Approved",
    "Contract Number": 50006,
    Description: "Conference room chairs",
    "Requested Award Date": "05-16-2025",
    "Request Documents": [],
    "Customer POC Name": "Heidi Handler",
    "Customer POC Email": "heidi.handler@zeta.com",
    "Attention To ( If different )": "",
    "Shipping Address: Street": "303 Birch St",
    "Shipping Address: Street 2": "Unit B",
    "Shipping Address: City": "Metropolis",
    "Shipping Address: State": "NY",
    "Shipping Address: Zipcode": "10001",
  },
  {
    id: 7,
    "Request Workflow": "Equipment Lease",
    "Request Created": "05-07-2025",
    "Request Creator": "Grace Gopher",
    "Next Step Approver": "Terry User",
    "Previous Approver": "Frank Finance",
    "Request Number": 1007,
    "Request Status": "Pending",
    "Contract Number": 50007,
    Description: "Generator rental",
    "Requested Award Date": "05-17-2025",
    "Request Documents": [],
    "Customer POC Name": "Ivan Inspector",
    "Customer POC Email": "ivan.inspector@theta.com",
    "Attention To ( If different )": "Judy Judge",
    "Shipping Address: Street": "404 Spruce St",
    "Shipping Address: Street 2": "",
    "Shipping Address: City": "Gotham",
    "Shipping Address: State": "NJ",
    "Shipping Address: Zipcode": "07097",
  },
  {
    id: 8,
    "Request Workflow": "Software License",
    "Request Created": "05-08-2025",
    "Request Creator": "Heidi Handler",
    "Next Step Approver": "Kara Admin",
    "Previous Approver": "Grace Gopher",
    "Request Number": 1008,
    "Request Status": "In Progress",
    "Contract Number": 50008,
    Description: "Graphic editing suite",
    "Requested Award Date": "05-18-2025",
    "Request Documents": [],
    "Customer POC Name": "Judy Judge",
    "Customer POC Email": "judy.judge@iota.com",
    "Attention To ( If different )": "",
    "Shipping Address: Street": "505 Willow St",
    "Shipping Address: Street 2": "",
    "Shipping Address: City": "Star City",
    "Shipping Address: State": "CA",
    "Shipping Address: Zipcode": "90001",
  },
  {
    id: 9,
    "Request Workflow": "Maintenance Request",
    "Request Created": "05-09-2025",
    "Request Creator": "Ivan Inspector",
    "Next Step Approver": "Dan User",
    "Previous Approver": "Heidi Handler",
    "Request Number": 1009,
    "Request Status": "Approved",
    "Contract Number": 50009,
    Description: "Elevator inspection",
    "Requested Award Date": "05-19-2025",
    "Request Documents": [],
    "Customer POC Name": "Alice Admin",
    "Customer POC Email": "alice.admin@kappa.com",
    "Attention To ( If different )": "",
    "Shipping Address: Street": "606 Chestnut St",
    "Shipping Address: Street 2": "",
    "Shipping Address: City": "Central City",
    "Shipping Address: State": "TX",
    "Shipping Address: Zipcode": "73301",
  },
  {
    id: 10,
    "Request Workflow": "Supply Reorder",
    "Request Created": "05-10-2025",
    "Request Creator": "Judy Judge",
    "Next Step Approver": "Matt User",
    "Previous Approver": "Ivan Inspector",
    "Request Number": 1010,
    "Request Status": "Pending",
    "Contract Number": 50010,
    Description: "Paper reams",
    "Requested Award Date": "05-20-2025",
    "Request Documents": [],
    "Customer POC Name": "Bob Buyer",
    "Customer POC Email": "bob.buyer@lambda.com",
    "Attention To ( If different )": "",
    "Shipping Address: Street": "707 Redwood St",
    "Shipping Address: Street 2": "",
    "Shipping Address: City": "Coast City",
    "Shipping Address: State": "WA",
    "Shipping Address: Zipcode": "98004",
  },
  {
    id: 11,
    "Request Workflow": "Purchase Order",
    "Request Created": "05-11-2025",
    "Request Creator": "Alice Admin",
    "Next Step Approver": "Jane Super",
    "Previous Approver": "Judy Judge",
    "Request Number": 1011,
    "Request Status": "In Progress",
    "Contract Number": 50011,
    Description: "Computer monitors",
    "Requested Award Date": "05-21-2025",
    "Request Documents": [],
    "Customer POC Name": "Carol Contact",
    "Customer POC Email": "carol.contact@mu.com",
    "Attention To ( If different )": "",
    "Shipping Address: Street": "808 Poplar St",
    "Shipping Address: Street 2": "",
    "Shipping Address: City": "Metropolis",
    "Shipping Address: State": "NY",
    "Shipping Address: Zipcode": "10001",
  },
  {
    id: 12,
    "Request Workflow": "Equipment Lease",
    "Request Created": "05-12-2025",
    "Request Creator": "Bob Buyer",
    "Next Step Approver": "Kara Admin",
    "Previous Approver": "Alice Admin",
    "Request Number": 1012,
    "Request Status": "Approved",
    "Contract Number": 50012,
    Description: "Safety helmets",
    "Requested Award Date": "05-22-2025",
    "Request Documents": [],
    "Customer POC Name": "Dave Delivery",
    "Customer POC Email": "dave.delivery@nu.com",
    "Attention To ( If different )": "",
    "Shipping Address: Street": "909 Sycamore St",
    "Shipping Address: Street 2": "Bldg A",
    "Shipping Address: City": "Gotham",
    "Shipping Address: State": "NJ",
    "Shipping Address: Zipcode": "07097",
  },
  {
    id: 13,
    "Request Workflow": "Software License",
    "Request Created": "05-13-2025",
    "Request Creator": "Carol Contact",
    "Next Step Approver": "Dan User",
    "Previous Approver": "Bob Buyer",
    "Request Number": 1013,
    "Request Status": "Pending",
    "Contract Number": 50013,
    Description: "CAD software",
    "Requested Award Date": "05-23-2025",
    "Request Documents": [],
    "Customer POC Name": "Eve Engineer",
    "Customer POC Email": "eve.engineer@xi.com",
    "Attention To ( If different )": "Frank Finance",
    "Shipping Address: Street": "1010 Palm St",
    "Shipping Address: Street 2": "",
    "Shipping Address: City": "Star City",
    "Shipping Address: State": "CA",
    "Shipping Address: Zipcode": "90001",
  },
  {
    id: 14,
    "Request Workflow": "Maintenance Request",
    "Request Created": "05-14-2025",
    "Request Creator": "Dave Delivery",
    "Next Step Approver": "Matt User",
    "Previous Approver": "Carol Contact",
    "Request Number": 1014,
    "Request Status": "In Progress",
    "Contract Number": 50014,
    Description: "Fire alarm test",
    "Requested Award Date": "05-24-2025",
    "Request Documents": [],
    "Customer POC Name": "Grace Gopher",
    "Customer POC Email": "grace.gopher@omicron.com",
    "Attention To ( If different )": "",
    "Shipping Address: Street": "1111 Cedar St",
    "Shipping Address: Street 2": "",
    "Shipping Address: City": "Central City",
    "Shipping Address: State": "TX",
    "Shipping Address: Zipcode": "73301",
  },
  {
    id: 15,
    "Request Workflow": "Supply Reorder",
    "Request Created": "05-15-2025",
    "Request Creator": "Eve Engineer",
    "Next Step Approver": "Terry User",
    "Previous Approver": "Dave Delivery",
    "Request Number": 1015,
    "Request Status": "Approved",
    "Contract Number": 50015,
    Description: "Cleaning supplies",
    "Requested Award Date": "05-25-2025",
    "Request Documents": [],
    "Customer POC Name": "Heidi Handler",
    "Customer POC Email": "heidi.handler@pi.com",
    "Attention To ( If different )": "",
    "Shipping Address: Street": "1212 Maple St",
    "Shipping Address: Street 2": "",
    "Shipping Address: City": "Coast City",
    "Shipping Address: State": "WA",
    "Shipping Address: Zipcode": "98004",
  },
  {
    id: 16,
    "Request Workflow": "Purchase Order",
    "Request Created": "05-16-2025",
    "Request Creator": "Frank Finance",
    "Next Step Approver": "Dan User",
    "Previous Approver": "Eve Engineer",
    "Request Number": 1016,
    "Request Status": "Pending",
    "Contract Number": 50016,
    Description: "Office desks",
    "Requested Award Date": "05-26-2025",
    "Request Documents": [],
    "Customer POC Name": "Ivan Inspector",
    "Customer POC Email": "ivan.inspector@rho.com",
    "Attention To ( If different )": "",
    "Shipping Address: Street": "1313 Oak St",
    "Shipping Address: Street 2": "Ste 300",
    "Shipping Address: City": "Metropolis",
    "Shipping Address: State": "NY",
    "Shipping Address: Zipcode": "10001",
  },
  {
    id: 17,
    "Request Workflow": "Equipment Lease",
    "Request Created": "05-17-2025",
    "Request Creator": "Grace Gopher",
    "Next Step Approver": "Matt User",
    "Previous Approver": "Frank Finance",
    "Request Number": 1017,
    "Request Status": "In Progress",
    "Contract Number": 50017,
    Description: "Laptop rental",
    "Requested Award Date": "05-27-2025",
    "Request Documents": [],
    "Customer POC Name": "Judy Judge",
    "Customer POC Email": "judy.judge@sigma.com",
    "Attention To ( If different )": "",
    "Shipping Address: Street": "1414 Pine St",
    "Shipping Address: Street 2": "",
    "Shipping Address: City": "Gotham",
    "Shipping Address: State": "NJ",
    "Shipping Address: Zipcode": "07097",
  },
  {
    id: 18,
    "Request Workflow": "Software License",
    "Request Created": "05-18-2025",
    "Request Creator": "Heidi Handler",
    "Next Step Approver": "Terry User",
    "Previous Approver": "Grace Gopher",
    "Request Number": 1018,
    "Request Status": "Approved",
    "Contract Number": 50018,
    Description: "Antivirus subscription",
    "Requested Award Date": "05-28-2025",
    "Request Documents": [],
    "Customer POC Name": "Alice Admin",
    "Customer POC Email": "alice.admin@tau.com",
    "Attention To ( If different )": "",
    "Shipping Address: Street": "1515 Birch St",
    "Shipping Address: Street 2": "",
    "Shipping Address: City": "Star City",
    "Shipping Address: State": "CA",
    "Shipping Address: Zipcode": "90001",
  },
  {
    id: 19,
    "Request Workflow": "Maintenance Request",
    "Request Created": "05-19-2025",
    "Request Creator": "Ivan Inspector",
    "Next Step Approver": "Kara Admin",
    "Previous Approver": "Heidi Handler",
    "Request Number": 1019,
    "Request Status": "Pending",
    "Contract Number": 50019,
    Description: "Roof inspection",
    "Requested Award Date": "05-29-2025",
    "Request Documents": [],
    "Customer POC Name": "Bob Buyer",
    "Customer POC Email": "bob.buyer@upsilon.com",
    "Attention To ( If different )": "",
    "Shipping Address: Street": "1616 Cedar St",
    "Shipping Address: Street 2": "",
    "Shipping Address: City": "Central City",
    "Shipping Address: State": "TX",
    "Shipping Address: Zipcode": "73301",
  },
  {
    id: 20,
    "Request Workflow": "Supply Reorder",
    "Request Created": "05-20-2025",
    "Request Creator": "Judy Judge",
    "Next Step Approver": "Dan User",
    "Previous Approver": "Ivan Inspector",
    "Request Number": 1020,
    "Request Status": "Approved",
    "Contract Number": 50020,
    Description: "Coffee and snacks",
    "Requested Award Date": "05-30-2025",
    "Request Documents": [],
    "Customer POC Name": "Carol Contact",
    "Customer POC Email": "carol.contact@phi.com",
    "Attention To ( If different )": "",
    "Shipping Address: Street": "1717 Spruce St",
    "Shipping Address: Street 2": "",
    "Shipping Address: City": "Coast City",
    "Shipping Address: State": "WA",
    "Shipping Address: Zipcode": "98004",
  },
];
